# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_u',
            field=models.EmailField(blank=True, db_column='Email_U', max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='password', max_length=200),
        ),
    ]
