# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(db_column='CPF', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_u',
            field=models.CharField(db_column='Endereco_U', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='news',
            field=models.NullBooleanField(db_column='News', verbose_name='Deseja receber novidades ?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_u',
            field=models.IntegerField(db_column='Telefone_U', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(db_column='user_name', max_length=100, unique=True, verbose_name='username'),
        ),
    ]
