# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180514_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(db_column='CPF', unique=True, verbose_name='CPF'),
        ),
    ]
